<a href="https://colab.research.google.com/github/shivanshu-web/Bootcamp/blob/main/session7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Ai system compare data as points
#

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [15]:
students = pd.DataFrame({
    "name": ["Arnav", "kabir", "Ram", "parul", "sara"],
    "study_hours": [6, 3, 8, 2, 5],
    "attendance": [85, 70, 90, 60, 92],
    "previous_marks": [78, 55, 88, 35, 65],
    "final_marks": [82, 58, 91, 40, 70]
})

students


,name,study_hours,attendance,previous_marks,final_marks
0,Arnav,6,85,78,82
1,kabir,3,70,55,58
2,Ram,8,90,88,91
3,parul,2,60,35,40
4,sara,5,92,65,70


In [16]:
feature_columns = ["study_hours", "attendance", "previous_marks"]

student_vectors = students[feature_columns].values
print(student_vectors)


[[ 6 85 78]
 [ 3 70 55]
 [ 8 90 88]
 [ 2 60 35]
 [ 5 92 65]]


In [17]:

# Cosine similarity is a metric used to
#  measure the similarity between two vectors
#  by calculating the cosine of the angle between them.
#  Values closer to 1 indicate higher similarity.
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(student_vectors)

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=students["name"],
    columns=students["name"]
)

similarity_df

name,Arnav,kabir,Ram,parul,sara
name,,,,,
Arnav,1.000000,0.996913,0.999434,0.976875,0.991887
kabir,0.996913,1.000000,0.993724,0.990505,0.998651
Ram,0.999434,0.993724,1.000000,0.969344,0.987230
parul,0.976875,0.990505,0.969344,1.000000,0.996101
sara,0.991887,0.998651,0.987230,0.996101,1.000000


In [18]:
#embadding
from matplotlib import MatplotlibDeprecationWarning

#embeddings

#an embedding is a vector that represents MatplotlibDeprecationlarning
# words images products, users, sentences converted into embeddings


In [ ]:
# Tokeniztion
# Tokenization is the process of breaking text
#  into smaller units called tokens
# text -- tokens -- token id -- embaddings -- model




In [19]:
sentences = "the movie was not good"
token = sentences.lower().split()
print(token)

['the', 'movie', 'was', 'not', 'good']


In [20]:
vocab = {
    "the":1,
    "movie":2,
    "was":3,
    "not":4,
    "good":5

}

token_ids = [vocab[word] for word in token]
print(token_ids)

[1, 2, 3, 4, 5]


In [ ]:
# 1. Bag of Words (BoW) Model
# BoW only counts the words present in a sentence.

# 2. Sequence Model
# A sequence model keeps the order of words.

In [ ]:
# What is RNN?

# RNN (Recurrent Neural Network) is a type of
#  neural network designed for sequence data.

# It remembers information from previous inputs and
#  uses it while processing the current input.